INSERT INTO category (description) values ('american');
INSERT INTO category (description) values ('italian');
INSERT INTO category (description) values ('mexican');
INSERT INTO category (description) values ('fast food');
INSERT INTO unit_of_measure (description) values ('teaspoon');
INSERT INTO unit_of_measure (description) values ('tablespoon');
INSERT INTO unit_of_measure (description) values ('cup');
INSERT INTO unit_of_measure (description) values ('pinch');
INSERT INTO unit_of_measure (description) values ('ounce');
INSERT INTO unit_of_measure (description) values ('dash');